---
abstract: 'just use stuff'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: shit
requires:
  perl: v5.6.0
  strict: 0
  warnings: 0
version: 0.02
